export const moduleCategories = {
  "Accounts": "Accounts",
  "Import - Billing": "Accounts",

  "Employee Onboarding": "HR & Management",
  "Employee KYC": "HR & Management",
  "Customer KYC": "Customer KYC",
  "Import - DSR": "Import",
  Customer: "Customer",
  Documentation: "Import",
  Submission: "Import",
  "Import - Operations": "Import",
  "Import - Add": "Import",
  "Import - DO": "Import",
  "e-Sanchit": "Import",
  "Import Utility Tool": "Import",
  "LR Operations": "SRCC",
  "Inward Register": "Inward and Outward Register",
  "Outward Register": "Inward and Outward Register",
  "Exit Feedback": "HR & Management",
  "Tyre Maintenance": "SRCC",
  "SRCC Directories": "SRCC",
  "Directories": "Directories Mgt.",
  "SR CEL": "SRCC",
  RTO: "SRCC",
  Export: "Export",
  Screen1: "Screens",
  Screen2: "Screens",
  Screen3: "Screens",
  Screen4: "Screens",
  Screen5: "Screens",
  Screen6: "Screens",
};
